version: 2.1

orbs:
  goreleaser: hubci/goreleaser@1.0.0
  go: circleci/go@1.7.0
  terraform: circleci/terraform@2.1.0
  wait-for: cobli/wait-for@0.0.2

parameters:
  go-version:
    type: enum
    enum: ["1.16"]
    default: "1.16"

executors:
  default:
    docker:
      - image: cimg/go:<< pipeline.parameters.go-version >>

jobs:
  build:
    executor: default
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Build provider
          command: make install

  acceptance-tests:
    parameters:
      dokku-version:
        type: string
    environment:
      DOKKU_SSH_HOST: "127.0.0.1"
      DOKKU_SSH_PORT: 3022
      DOKKU_SSH_CERT: "/home/circleci/project/dokku-ssh"
      TF_LOG: DEBUG
      TF_LOG_PATH: terraform.log
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - go/install:
          version: << pipeline.parameters.go-version >>
      - go/load-cache
      - terraform/install:
          terraform_version: "1.0.9"
      - run:
          name: Pull dokku image
          command: |
            sudo docker pull dokku/dokku:<< parameters.dokku-version >>
      - run:
          name: Pull other images used in testing
          command: |
            sudo docker pull circleci/postgres:9.6.16-alpine-ram
            sudo docker pull circleci/redis:6.2.5
      - run:
          name: Setup dokku plugins
          command: |
            sudo mkdir -p /var/lib/dokku
            sudo cp .circleci/plugin-list /var/lib/dokku/
      - run:
          name: Start dokku container
          command: |
            sudo docker container run \
              --env DOKKU_HOSTNAME=dokku.me \
              --name dokku \
              --publish 3022:22 \
              --publish 8080:80 \
              --publish 8443:443 \
              --volume /var/lib/dokku:/mnt/dokku \
              --volume /var/run/docker.sock:/var/run/docker.sock \
              -d \
              dokku/dokku:<< parameters.dokku-version >>
      - run:
          name: Setup SSH key with container
          command: |
            ssh-keygen -t rsa -N "" -f dokku-ssh
            sudo docker cp dokku-ssh.pub dokku:/tmp/dokku-ssh.pub
            sudo docker exec dokku dokku ssh-keys:add dokku dokku-ssh.pub
      - wait-for/sh-command:
          timeout: 300
          sh-command: ssh -i dokku-ssh dokku@127.0.0.1 -p 3022
      - run:
          name: Run acceptance tests
          command: make testacc
      - store_artifacts:
          path: terraform.log

  release:
    parameters:
      dry-run:
        type: boolean
        default: false
    executor: default
    steps:
      - checkout
      - run:
          name: Import signing key
          command: |
            echo $OSS_SIGNING_KEY | base64 --decode | gpg --batch --no-tty --import --yes
            touch /tmp/.circleci-gpg-setup
            echo $OSS_SIGNING_PASS | gpg -a --detach-sign --passphrase-fd 0 --pinentry-mode loopback /tmp/.circleci-gpg-setup
      - goreleaser/install:
          version: "0.178.0"
      - run: goreleaser --release-notes=changes/<< pipeline.git.tag >>.md

workflows:
  build:
    jobs:
      - build

      - acceptance-tests:
          matrix:
            parameters:
              dokku-version: ["0.24.10", "0.25.7"]
          requires:
            - build

      - release:
          context:
            - github-release
            - oss-signing-key
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - /.*/
