version: 2.1

orbs:
  goreleaser: hubci/goreleaser@1.0.0

executors:
  default:
    docker:
      - image: cimg/go:1.16

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Build provider
          command: make install

  release:
    parameters:
      dry-run:
        type: boolean
        default: false
    executor: default
    steps:
      - checkout
      - run:
          name: Import signing key
          command: |
            echo $OSS_SIGNING_KEY | base64 --decode | gpg --batch --no-tty --import --yes
            touch /tmp/.circleci-gpg-setup
            echo $OSS_SIGNING_PASS | gpg -a --detach-sign --passphrase-fd 0 --pinentry-mode loopback /tmp/.circleci-gpg-setup
      - goreleaser/install:
          version: "0.173.2"
      - goreleaser/release:
          dry-run: << parameters.dry-run >>

workflows:
  build:
    jobs:
      - build

      - release:
          context:
            - github-release
            - oss-signing-key
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
                - /.*/

      - release:
          name: release-dry-run
          dry-run: true
          context:
            - github-release
            - oss-signing-key
          filters:
            branches:
              only:
                - main
          requires:
            - build
